name: Publish Package to npmjs
on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  publish:
    if: github.repository == 'bernoussama/mcplog'
    runs-on: ubuntu-latest
    permissions:
      contents: write # trusted publishing and changelog requirement
      id-token: write # trusted publishing requirement
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set node version to 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          # disable cache to avoid cache poisoning
          package-manager-cache: false

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm prepack

      - run: pnpm prepublishOnly

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
